# Generated by Django 5.0.3 on 2024-08-29 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
